<?php


namespace Hsioe\QuantOkxApi\Tests\rest;

use GuzzleHttp\Exception\GuzzleException;
use Hsioe\QuantOkxApi\OkxApi;
use Hsioe\QuantOkxApi\Rest\Apis\AssetApi;
use Hsioe\QuantOkxApi\Rest\Apis\Req\AssetBillsRequest;
use Hsioe\QuantOkxApi\Rest\Apis\Req\WithdrawalHistoryRequest;
use Hsioe\QuantOkxApi\Rest\Exception\OkxApiException;

class TestAssetApi extends ApiTestCase
{
    protected AssetApi $api;
    
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->api = OkxApi::asset($this->apiRequest);
    }
    
    /**
     * 获取历史记录
     *
     * @return void
     * @throws GuzzleException
     * @throws OkxApiException
     */
    public function testGetBills(): void
    {
        $req = new AssetBillsRequest([]);
        
        $res = $this->api->getBills($req);
        $this->assertEquals(0, $res['code']);
    }
    
    /**
     * 测试提笔历史
     *
     * @return void
     * @throws GuzzleException
     * @throws OkxApiException
     */
    public function testGetWithdrawalHistory(): void
    {
        $api = OkxApi::finance($this->apiRequest);
        
        $res = $api->getWithdrawalHistory(new WithdrawalHistoryRequest([]));
        $this->assertEquals(0, $res['code']);
    }
}